seed: 1566911444
device: "cuda:0"

logging:
  path: ./runs/
  experiment: freebase_nc_p1c2

data:
  path: ./data/preprocessed/Freebase_dhn_nc_unchanged.pt

model:
  learned_node_embeddings: true
  layers_config:
    - p1: [-1, 64, 1]
      c2: [-1, 64, 2]
  agg: null
  activation:
    name: ReLU
    kwargs:
      inplace: false
  homconv_kwargs:
    mapping_chunk_size: 100000
    checkpoint_chunks: true

training:
  epochs: 200
  loss:
    name: CrossEntropyLoss
    kwargs:
      reduction: mean
  optimizer:
    name: AdamW
    kwargs:
      lr: 0.005
      weight_decay: 0.001
      betas: [0.9, 0.999]
  lr_scheduling:
    name: null
    kwargs: {}
